import type { FoamPreset } from "./types.js";

export const FOAM_PRESETS: FoamPreset[] = [
  {
    id: "ocean-whitecaps",
    name: "Ocean Whitecaps",
    category: "foam",
    description: "Scattered whitecaps on wind-driven ocean waves",
    tags: ["ocean", "whitecaps", "wind", "wave-crests"],
    foamColor: "#F0F0F0",
    foamAmount: 0.5,
    whitecapThreshold: 0.6,
    foamTrailLength: 0.3,
    langmuirStrength: 0.2,
    bubbleIntensity: 0.15,
  },
  {
    id: "surf-foam",
    name: "Surf Foam",
    category: "foam",
    description: "Dense churning foam in the breaking wave zone",
    tags: ["surf", "breaking", "dense", "shore"],
    foamColor: "#FFFFFF",
    foamAmount: 0.8,
    whitecapThreshold: 0.3,
    foamTrailLength: 0.6,
    langmuirStrength: 0,
    bubbleIntensity: 0.4,
  },
  {
    id: "gentle-foam",
    name: "Gentle Foam",
    category: "foam",
    description: "Subtle foam lines on calm water surface",
    tags: ["gentle", "calm", "subtle", "lines"],
    foamColor: "#E8E8E8",
    foamAmount: 0.2,
    whitecapThreshold: 0.8,
    foamTrailLength: 0.15,
    langmuirStrength: 0.4,
    bubbleIntensity: 0.05,
  },
  {
    id: "storm-foam",
    name: "Storm Foam",
    category: "foam",
    description: "Heavy foam and spray from storm-force winds",
    tags: ["storm", "heavy", "spray", "wind"],
    foamColor: "#F8F8F8",
    foamAmount: 0.9,
    whitecapThreshold: 0.2,
    foamTrailLength: 0.8,
    langmuirStrength: 0.6,
    bubbleIntensity: 0.6,
  },
];
