import type { IcePreset } from "./types.js";

export const ICE_PRESETS: IcePreset[] = [
  {
    id: "frozen-lake",
    name: "Frozen Lake",
    category: "ice",
    description: "Thick frozen lake surface with deep cracks and trapped air bubbles",
    tags: ["frozen", "lake", "thick", "cracks"],
    iceThickness: 0.8,
    crackDensity: 0.4,
    frostIntensity: 0.3,
    snowCover: 0.1,
    iceColor: "#C0D8E8",
    crackColor: "#2A4A6A",
  },
  {
    id: "thin-ice",
    name: "Thin Ice",
    category: "ice",
    description: "Thin translucent ice revealing dark water beneath",
    tags: ["thin", "translucent", "fragile", "dark"],
    iceThickness: 0.2,
    crackDensity: 0.7,
    frostIntensity: 0.1,
    snowCover: 0,
    iceColor: "#90B0C8",
    crackColor: "#1A2A3A",
  },
  {
    id: "pack-ice",
    name: "Pack Ice",
    category: "ice",
    description: "Broken pack ice with snow-covered chunks and exposed water",
    tags: ["pack-ice", "broken", "snow", "arctic"],
    iceThickness: 0.6,
    crackDensity: 0.8,
    frostIntensity: 0.5,
    snowCover: 0.6,
    iceColor: "#D8E8F0",
    crackColor: "#1A3050",
  },
  {
    id: "frost-glass",
    name: "Frost Glass",
    category: "ice",
    description: "Delicate frost crystal patterns on glass-clear ice",
    tags: ["frost", "glass", "crystal", "delicate"],
    iceThickness: 0.4,
    crackDensity: 0.2,
    frostIntensity: 0.9,
    snowCover: 0,
    iceColor: "#E0F0F8",
    crackColor: "#80A0B8",
  },
];
