import type { ReflectionPreset } from "./types.js";

export const REFLECTION_PRESETS: ReflectionPreset[] = [
  {
    id: "calm-lake-reflection",
    name: "Calm Lake",
    category: "reflection",
    description: "Near-perfect mirror reflection on still lake water with minimal ripple",
    tags: ["calm", "lake", "mirror", "still"],
    skyColor: "#87CEEB",
    terrainColor: "#3A5A30",
    reflectionStrength: 0.9,
    reflectionBlur: 0.2,
    reflectionDistortion: 0.1,
    waterlinePosition: 0.5,
  },
  {
    id: "rippled-reflection",
    name: "Rippled Reflection",
    category: "reflection",
    description: "Broken reflection on water with moderate ripple distortion",
    tags: ["rippled", "broken", "water", "wind"],
    skyColor: "#6AAEDC",
    terrainColor: "#2A4A28",
    reflectionStrength: 0.65,
    reflectionBlur: 0.5,
    reflectionDistortion: 0.5,
    waterlinePosition: 0.5,
  },
  {
    id: "dark-water-reflection",
    name: "Dark Water",
    category: "reflection",
    description: "Deep dark water reflection with strong darkening and subtle movement",
    tags: ["dark", "deep", "moody", "dramatic"],
    skyColor: "#4A6A8A",
    terrainColor: "#1A2A18",
    reflectionStrength: 0.5,
    reflectionBlur: 0.6,
    reflectionDistortion: 0.2,
    waterlinePosition: 0.5,
  },
  {
    id: "golden-reflection",
    name: "Golden Reflection",
    category: "reflection",
    description: "Warm golden hour reflection with amber-tinted sky and terrain colors",
    tags: ["golden", "warm", "sunset", "amber"],
    skyColor: "#E8A040",
    terrainColor: "#4A3A20",
    reflectionStrength: 0.8,
    reflectionBlur: 0.3,
    reflectionDistortion: 0.3,
    waterlinePosition: 0.5,
  },
];
