import type { ShorelinePreset } from "./types.js";

export const SHORELINE_PRESETS: ShorelinePreset[] = [
  {
    id: "sandy-beach",
    name: "Sandy Beach",
    category: "shoreline",
    description: "Wide sandy beach with gentle foam line and shell debris",
    tags: ["sandy", "beach", "foam", "gentle"],
    shoreType: "beach",
    width: 0.08,
    color: "#D4C4A0",
    wetColor: "#B0A080",
    foamLine: true,
    foamIntensity: 0.5,
    debrisType: "shells",
    waveBreakStyle: "spilling",
  },
  {
    id: "rocky-shore",
    name: "Rocky Shore",
    category: "shoreline",
    description: "Rugged rocky shoreline with crashing surf",
    tags: ["rocky", "rugged", "surf", "dramatic"],
    shoreType: "rocky",
    width: 0.06,
    color: "#6A6A5A",
    wetColor: "#4A4A3A",
    foamLine: true,
    foamIntensity: 0.8,
    debrisType: "seaweed",
    waveBreakStyle: "plunging",
  },
  {
    id: "muddy-riverbank",
    name: "Muddy Riverbank",
    category: "shoreline",
    description: "Soft muddy bank along a river",
    tags: ["muddy", "riverbank", "soft", "wet"],
    shoreType: "riverbank",
    width: 0.05,
    color: "#6A5A3A",
    wetColor: "#4A3A20",
    foamLine: false,
    foamIntensity: 0,
    debrisType: "none",
    waveBreakStyle: "surging",
  },
  {
    id: "grassy-bank",
    name: "Grassy Bank",
    category: "shoreline",
    description: "Gentle grassy slope meeting the water",
    tags: ["grassy", "bank", "gentle", "green"],
    shoreType: "riverbank",
    width: 0.07,
    color: "#5A7A3A",
    wetColor: "#4A6030",
    foamLine: false,
    foamIntensity: 0,
    debrisType: "none",
    waveBreakStyle: "surging",
  },
  {
    id: "tidal-flat",
    name: "Tidal Flat",
    category: "shoreline",
    description: "Exposed tidal flat with wet sand and pools",
    tags: ["tidal", "flat", "wet", "pools"],
    shoreType: "tidal-flat",
    width: 0.1,
    color: "#B0A080",
    wetColor: "#8A8068",
    foamLine: true,
    foamIntensity: 0.3,
    debrisType: "seaweed",
    waveBreakStyle: "surging",
  },
  {
    id: "cliff-base",
    name: "Cliff Base",
    category: "shoreline",
    description: "Narrow strip at the base of sea cliffs",
    tags: ["cliff", "base", "narrow", "dramatic"],
    shoreType: "cliff-base",
    width: 0.03,
    color: "#5A5A4A",
    wetColor: "#3A3A2A",
    foamLine: true,
    foamIntensity: 0.9,
    debrisType: "pebbles",
    waveBreakStyle: "plunging",
  },
  {
    id: "marsh-edge",
    name: "Marsh Edge",
    category: "shoreline",
    description: "Marshy waterline with organic matter and partial vegetation",
    tags: ["marsh", "swamp", "organic", "vegetation"],
    shoreType: "marsh",
    width: 0.12,
    color: "#4A5A30",
    wetColor: "#3A4A28",
    foamLine: false,
    foamIntensity: 0,
    debrisType: "seaweed",
    waveBreakStyle: "surging",
  },
];
