import type { SurfacePreset } from "./types.js";

export const SURFACE_PRESETS: SurfacePreset[] = [
  // --- Calm algorithm (stripe compositing) ---
  {
    id: "still-lake",
    name: "Still Lake",
    category: "surface",
    description: "Calm, mirror-like lake surface with minimal ripples",
    tags: ["calm", "lake", "mirror", "peaceful"],
    algorithm: "calm",
    waterlinePosition: 0.6,
    waveHeight: 0.3,
    wavePeriod: 0.8,
    waveComplexity: 0.2,
    chop: 0,
    surfaceColor: "#2A4A6B",
    depthColor: "#152535",
    shimmerIntensity: 0.15,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "pond",
    name: "Pond",
    category: "surface",
    description: "Small quiet pond with subtle surface movement",
    tags: ["pond", "quiet", "small", "still"],
    algorithm: "calm",
    waterlinePosition: 0.7,
    waveHeight: 0.15,
    wavePeriod: 0.6,
    waveComplexity: 0.15,
    chop: 0,
    surfaceColor: "#2A4050",
    depthColor: "#151E28",
    shimmerIntensity: 0.1,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "misty-lake",
    name: "Misty Lake",
    category: "surface",
    description: "Still lake surface shrouded in atmospheric mist",
    tags: ["misty", "lake", "atmospheric", "moody"],
    algorithm: "calm",
    waterlinePosition: 0.55,
    waveHeight: 0.1,
    wavePeriod: 1.0,
    waveComplexity: 0.1,
    chop: 0,
    surfaceColor: "#3A5A6A",
    depthColor: "#1A2A35",
    shimmerIntensity: 0.05,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "moonlit-water",
    name: "Moonlit Water",
    category: "surface",
    description: "Dark water with a single bright moonlight reflection path",
    tags: ["moonlit", "night", "dark", "atmospheric"],
    algorithm: "calm",
    waterlinePosition: 0.5,
    waveHeight: 0.2,
    wavePeriod: 0.7,
    waveComplexity: 0.2,
    chop: 0,
    surfaceColor: "#0A1520",
    depthColor: "#050A10",
    shimmerIntensity: 0.5,
    flowDirection: 0,
    flowStrength: 0,
  },
  // --- Ocean algorithm (Gerstner waves) ---
  {
    id: "choppy-sea",
    name: "Choppy Sea",
    category: "surface",
    description: "Rough ocean surface with strong waves and whitecaps",
    tags: ["ocean", "rough", "waves", "dramatic"],
    algorithm: "ocean",
    waterlinePosition: 0.55,
    waveHeight: 0.8,
    wavePeriod: 0.4,
    waveComplexity: 0.7,
    chop: 0.6,
    surfaceColor: "#1A3A5C",
    depthColor: "#0A1A2E",
    shimmerIntensity: 0.3,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "ocean-swell",
    name: "Ocean Swell",
    category: "surface",
    description: "Deep ocean with long rolling swells",
    tags: ["ocean", "swell", "deep", "rolling"],
    algorithm: "ocean",
    waterlinePosition: 0.5,
    waveHeight: 0.6,
    wavePeriod: 0.8,
    waveComplexity: 0.4,
    chop: 0.2,
    surfaceColor: "#1A3050",
    depthColor: "#0A1828",
    shimmerIntensity: 0.2,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "stormy-ocean",
    name: "Stormy Ocean",
    category: "surface",
    description: "Violent storm-tossed ocean with towering waves",
    tags: ["stormy", "ocean", "violent", "dramatic"],
    algorithm: "ocean",
    waterlinePosition: 0.45,
    waveHeight: 1.0,
    wavePeriod: 0.3,
    waveComplexity: 0.9,
    chop: 0.9,
    surfaceColor: "#152A40",
    depthColor: "#080E18",
    shimmerIntensity: 0.1,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "tropical-shallows",
    name: "Tropical Shallows",
    category: "surface",
    description: "Clear turquoise shallow water over sandy bottom",
    tags: ["tropical", "shallow", "turquoise", "clear"],
    algorithm: "ocean",
    waterlinePosition: 0.6,
    waveHeight: 0.3,
    wavePeriod: 0.5,
    waveComplexity: 0.3,
    chop: 0.1,
    surfaceColor: "#2A8A8A",
    depthColor: "#1A5A5A",
    shimmerIntensity: 0.4,
    flowDirection: 0,
    flowStrength: 0,
  },
  {
    id: "coastal-surf",
    name: "Coastal Surf",
    category: "surface",
    description: "Breaking waves in the surf zone near shore",
    tags: ["coastal", "surf", "breaking", "shore"],
    algorithm: "ocean",
    waterlinePosition: 0.6,
    waveHeight: 0.7,
    wavePeriod: 0.45,
    waveComplexity: 0.5,
    chop: 0.4,
    surfaceColor: "#2A5A7A",
    depthColor: "#152A3A",
    shimmerIntensity: 0.25,
    flowDirection: 0,
    flowStrength: 0,
  },
  // --- Flow algorithm (flow-field ripples) ---
  {
    id: "mountain-stream",
    name: "Mountain Stream",
    category: "surface",
    description: "Clear mountain stream with visible ripple patterns and current",
    tags: ["stream", "clear", "mountain", "fresh", "flowing"],
    algorithm: "flow",
    waterlinePosition: 0.75,
    waveHeight: 0.4,
    wavePeriod: 0.3,
    waveComplexity: 0.5,
    chop: 0.3,
    surfaceColor: "#3A6A7A",
    depthColor: "#1A3540",
    shimmerIntensity: 0.4,
    flowDirection: Math.PI / 2,
    flowStrength: 0.7,
  },
  {
    id: "river",
    name: "River",
    category: "surface",
    description: "Wide river with moderate current and surface texture",
    tags: ["river", "moderate", "flowing", "wide"],
    algorithm: "flow",
    waterlinePosition: 0.65,
    waveHeight: 0.3,
    wavePeriod: 0.5,
    waveComplexity: 0.3,
    chop: 0.1,
    surfaceColor: "#2E5060",
    depthColor: "#152830",
    shimmerIntensity: 0.2,
    flowDirection: Math.PI / 2,
    flowStrength: 0.4,
  },
];
